### ISSUE TITLE
Come back to this project

### ISSUE THREAD

**Issue by hezi2** [Curlybear/Socrates#13]

**Comment by hezi2** [comment]
http://api.erepublik.com/

**Comment by hezi2** [comment]
or let me make a new one from what you developed, i could build an entire website around the code you provided

**Comment by Curlybear** [comment]
The api you're mentioning is the official api of the game, which is neither under my control or maintained anymore. I didn't develop an api, if you read my code you'll notice I only use https://erepublik.tools/ 's api.
